version: '3'

services: 
  
  api:
    build: 
      context: tasks-api
    container_name: api
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s /usr/src/app/entrypoint.sh
    networks:
      - tasks-network
    volumes:
      - ./tasks-api:/usr/src/app
    ports:
      - "3333:3333"
    depends_on:
      - db
      
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=tasksdb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - tasks-network

networks:
  tasks-network:
    driver: bridge