version: '3'

services: 
  
  api:
    build: 
      context: tasks-api
    container_name: api
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s /usr/src/app/entrypoint.sh
    networks:
      - tasks-network
    volumes:
      - ./tasks-api:/usr/src/app
    ports:
      - "3333:3333"
    depends_on:
      - db
      - amqp
      
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "33061:3306"
    volumes: 
      - ./scripts:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=managementdb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - tasks-network

  amqp:
    image: rabbitmq:3.9-management-alpine
    container_name: 'amqp'
    restart: always
    environment:
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_USER=guest
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - tasks-network 
      

networks:
  tasks-network:
    driver: bridge